name: trigger remote-control
on: [push]
  ref: yasser
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in target repository
        run: |
          curl -XPOST -u "${{ env.USERNAME }}:${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/lamasatech/remote-control/dispatches" \
            -d '{"event_type": "triggered-event"}'
